### ISSUE TITLE
Internationalization(i18n) support

### ISSUE THREAD

**Issue by gaotxg** [manjaro/manjaro-welcome#25]
Manjaro is a distribution used in the whole world, and aims to be user-friendly. Therefore, it's necessary to make every Manjaro specific apps have internationalization support.

**Comment by prescott66** [comment]
i agree. manjaro welcome greeter need localization support.

**Comment by andrebrait** [comment]
I'm looking forward to to contribute by implementing localization support to the Manjaro Welcome Greeter. If I'm not mistaken, it's quite simple, as it's based on Python. I'm somewhat experienced with python. If you guys think it's viable, please post another answer to this issue or contact me somehow and I'll start coding as soon as I can.

**Comment by Huluti** [comment]
Done with manjaro-hello.
