### ISSUE TITLE
Chat-room link fails on welcome 20160703-1

### ISSUE THREAD

**Issue by methuzla** [manjaro/manjaro-welcome#27]
majaro-welcome 20160703-1

The link to chat-room on manjaro welcome panel reads:
https://kiwiirc.com/client/%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20irc.freenode.net/?nick=manjaro-web|?#manjaro

(which predicatbly though initially puzzlingly fails to find that server "%20%20....")

I suggest a change to 
https://kiwiirc.com/client/irc.freenode.net/?nick=manjaro-web|?#manjaro
or similar.

which works better.

:)

**Comment by philmmanjaro** [comment]
Current source code is:

```
        elif uri == 'manjaro-irc':
            Popen([
                'xdg-open',
                """https://kiwiirc.com/client/\
                irc.freenode.net/?nick=manjaro-web|?#manjaro"""
            ])
```
On which edition of Manjaro do you have the issue?
