### ISSUE TITLE
include link to user guide

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-welcome#29]
it looks like the [manjaro user guide](https://github.com/manjaro/manjaro-user-guide) / manjaro-documentation is updated. please include a link to it in manjaro-welcome.

i am not 100% sure, but i think manjaro-welcome has already included a link to the user guide instead of a link to the wiki in the past. i could be wrong, though.

this change is being discussed in the forum as well: https://forum.manjaro.org/t/manjaro-documentation-in-welcome-screen/10539

**Comment by Huluti** [comment]
I think I'll fix that in manjaro-hello.
