### ISSUE TITLE
Does really need python2 support ?

### ISSUE THREAD

**Issue by Huluti** [manjaro/manjaro-welcome#33]
Hi !
When today python 3 is the default python version on most systems, including Manjaro, why keep support for python 2 ?

**Comment by jonathonf** [comment]
Python 3 is not the default on any system beyond Arch-based distros, `/usr/bin/python` is and will be python2 for the foreseeable future: https://www.python.org/dev/peps/pep-0394/

I'd suggest that switching Manjaro Welcome to use `/usr/bin/python3` as its shebang will limit its portability though that might be the right thing to do.
